# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 71acb69d104994c4ef78996efc14a9de62baefe05fb7ba760968c6c9dad4b45913872a5e36901e9240545135968e5e1ef1b4fd33ed66a2f9c6539b1cb2550625

test:
  secret_key_base: 911594d090293e28ca7434c315dd12ca192f00d2d42fb67f0c6d40b7e1d383ee314a49c58448101a86243216eae270dd61280543fffd2e8ba81a51f68f5a4aa7

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
